feat: About page
bjerkio/website pull request #107
Opened 2021-03-24 13:05 UTC by dkostenko-bjerk

Close #103

2021-03-24 22:02 UTC, cobraz approved these changes
🙏

2021-03-24 22:02 UTC, cobraz commented on web/src/pages/about.tsx
> +const boxesData = [
I talk about this in #108 as well.

It is relevant here as well, IMHO. 

re https://github.com/bjerkio/website/pull/108#discussion_r600901491

2021-03-25 07:42 UTC, AnneMatilde requested changes
Content looks good! The header background is missing on scroll. And the font is squeezed, but we have mentioned that in a different PR.

2021-03-25 09:58 UTC, AnnaBjerk commented
@AnneMatilde 

> Content looks good! The header background is missing on scroll. And the font is squeezed, but we have mentioned that in a different PR.

Indeed, I made a new issue regarding header here:  #113  It pops up with wite letters and white background when opening the page and if the page is refreshed changes color to black. 

@dkostenko-bjerk

2021-03-25 16:21 UTC, dkostenko-bjerk commented
Fixed bugs with the header

2021-03-26 08:55 UTC, cobraz approved these changes

2021-03-26 09:44 UTC, AnnaBjerk approved these changes
Looks good

2021-03-26 14:14 UTC, dkostenko-bjerk commented
@AnneMatilde  Is #94 fixed here too?

2021-03-27 12:40 UTC, AnneMatilde requested changes
The about-page looks good! Please fix radius on button. 

This is how it looks now:
![image](https://user-images.githubusercontent.com/54155334/112721017-eedafb80-8f01-11eb-99a7-7b8fcf11ebb7.png)


How it should look:
![image](https://user-images.githubusercontent.com/54155334/112720992-d539b400-8f01-11eb-9e3b-b2740524f066.png)

2021-03-27 12:54 UTC, dkostenko-bjerk commented
@AnneMatilde , done

2021-03-29 15:41 UTC, AnneMatilde commented
Sorry, #94 Looks good here @dkostenko-bjerk – except for the background on contact and footer.
Button is better, but seems like the font is wrong? 
![image](https://user-images.githubusercontent.com/54155334/112862201-cf84cf80-90b5-11eb-83ff-7c042d321e12.png)

2021-03-30 07:29 UTC, dkostenko-bjerk commented
@AnneMatilde it's fixed

2021-03-30 10:09 UTC, cobraz approved these changes

2021-03-30 10:51 UTC, AnneMatilde approved these changes
Design looks good!

2021-03-30 10:54 UTC, merged