feat: Contact page
bjerkio/website pull request #109
Opened 2021-03-24 13:06 UTC by dkostenko-bjerk

Close #105

2021-03-24 22:03 UTC, cobraz approved these changes
LGTM 🎉

2021-03-24 22:03 UTC, cobraz commented on web/src/components/contact/employee-list-item.tsx
> +  photo?: any;
Why `any`? We have activated `@typescript-eslint/no-explicit-any`.

2021-03-24 22:03 UTC, cobraz commented on web/src/pages/contact.tsx
> +  {
I talk about this in #108 as well.

It is relevant here as well, IMHO. 

re https://github.com/bjerkio/website/pull/108#discussion_r600901491

2021-03-25 07:51 UTC, AnneMatilde requested changes
The text has the wrong size and weight – this is throughout the subpages. 
This is how it looks now:
![image](https://user-images.githubusercontent.com/54155334/112437147-eab6ae80-8d46-11eb-87ea-d3c68953d198.png)

And this is how it should look:
![image](https://user-images.githubusercontent.com/54155334/112437175-f3a78000-8d46-11eb-84ae-1471a84e3fce.png)

Picture of Niklas and Anna is blury.

Header is missing background on scroll.

Text underneath the pictures is also too small and squeezed:
![image](https://user-images.githubusercontent.com/54155334/112437266-0d48c780-8d47-11eb-9203-cdcda3d5ceba.png)

2021-03-25 11:39 UTC, dkostenko-bjerk commented
@AnneMatilde where can I get not blurry images?

2021-03-25 11:43 UTC, cobraz commented
> @AnneMatilde where can I get not blurry images?

Isn't the designs made in Adobe XD or Figma? Should be possible to export the assets directly.

/cc @AnneMatilde

2021-03-25 12:07 UTC, dkostenko-bjerk commented
@cobraz They are blurry there too

@seacurrent @AnnaBjerk Do you have non-blurry photos?

2021-03-25 12:23 UTC, AnneMatilde commented
The design is in Adobe XD. The images are blury to begin with – so we need better images.

2021-03-25 12:42 UTC, seacurrent commented
![BNS](https://user-images.githubusercontent.com/70881117/112474364-d1762800-8d6f-11eb-8f48-903ffa577296.jpg)
You could probably use this profile pic.

2021-03-25 13:15 UTC, cobraz commented
This is actually a nice test of our user experience, maybe everyone can upload their own pictures?

re #91

2021-03-25 14:01 UTC, AnnaBjerk commented
> The text has the wrong size and weight – this is throughout the subpages.
> This is how it looks now:
> ![image](https://user-images.githubusercontent.com/54155334/112437147-eab6ae80-8d46-11eb-87ea-d3c68953d198.png)
> 
> And this is how it should look:
> ![image](https://user-images.githubusercontent.com/54155334/112437175-f3a78000-8d46-11eb-84ae-1471a84e3fce.png)
> 
> Picture of Niklas and Anna is blury.
> 
> Header is missing background on scroll.
> 
> Text underneath the pictures is also too small and squeezed:
> ![image](https://user-images.githubusercontent.com/54155334/112437266-0d48c780-8d47-11eb-9203-cdcda3d5ceba.png)

I have made a separate issue on the disappearing background in header. I'll make an issue on text as well. As I understood the text is easier to fix after the pages have been merged. Is this correct, @dkostenko-bjerk ?

2021-03-25 14:02 UTC, dkostenko-bjerk commented
@AnnaBjerk Yes

2021-03-25 14:05 UTC, AnnaBjerk commented
@AnneMatilde Could you aprove this for now and I'll make an issue on text using the photos you posted so that we can keep issues separated and in smaller pieces 😸

2021-03-25 14:07 UTC, AnnaBjerk approved these changes

2021-03-25 14:09 UTC, AnnaBjerk commented
> They are blurry there too
> 
> @AnnaBjerk Do you have non-blurry photos?

I'll try to find the bigger original. If that helps?

2021-03-25 19:31 UTC, cobraz commented
Images can be replaced later, we don't need to wait for that :)

2021-03-25 19:39 UTC, AnnaBjerk commented
> Images can be replaced later, we don't need to wait for that :)

Agreed. Let's land this!

2021-03-25 19:42 UTC, merged

2021-03-25 19:46 UTC, AnnaBjerk commented
> They are blurry there too
> 
> @AnnaBjerk Do you have non-blurry photos?

![20191118_port-f](https://user-images.githubusercontent.com/73297506/112534203-14a1bc80-8dab-11eb-9d95-d968135884d5.jpg)

/cc: @dkostenko-bjerk