fix: Fix button design
bjerkio/website pull request #112
Opened 2021-03-24 16:27 UTC by dkostenko-bjerk

Close #92

2021-03-24 22:04 UTC, cobraz approved these changes

2021-03-25 07:53 UTC, AnneMatilde requested changes
Button looks way better now, but the text inside is squeezed.

2021-03-25 09:02 UTC, cobraz commented
> Button looks way better now, but the text inside is squeezed.

IMHO: This can also be postponed to everything is landed, and opened as a separate issue/PR.

/cc @dkostenko-bjerk

2021-03-26 10:59 UTC, AnneMatilde commented
Agree!

2021-03-26 12:36 UTC, merged