fix: Contact footer padding, footer margin
bjerkio/website pull request #144
Opened 2021-03-31 11:36 UTC by dkostenko-bjerk

Closes #143

2021-03-31 11:58 UTC, cobraz approved these changes

2021-03-31 12:01 UTC, AnneMatilde requested changes
Contact form is not aligned
![image](https://user-images.githubusercontent.com/54155334/113141068-85245f80-9229-11eb-80f8-2ab77c82c881.png)

Footer looks good!

2021-03-31 12:18 UTC, dkostenko-bjerk commented
@AnneMatilde fixed

2021-03-31 12:40 UTC, cobraz approved these changes

2021-04-06 07:09 UTC, AnnaBjerk commented
@AnneMatilde Could you please review this again? It's supposed to be fixed now.

2021-04-18 11:06 UTC, closed without merging